# Generated by Django 5.1.1 on 2024-09-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', upload_to='avatars/'),
        ),
    ]
